name: docs_pages_workflow

on:
  push:
    branches: [ main ]

permissions:
  contents: write 

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0 # fetch all commits and branches
        # ref: main # only fetches the main branch, to fetch multiple probabaly needs to be done like bellow

# - name: Fetch specific branches
#  run: |
#    git fetch origin main:refs/remotes/origin/main
#    git fetch origin jazzy:refs/remotes/origin/jazzy

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r required_packages.txt

      - name: Build docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          bash docs/buildDocs.sh
